### ISSUE TITLE
VT Contract Review

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/housekeeping#1]
We've been forwarded a "service provider" contract to review.

**Comment by laynelafrance** [comment]
Reviewed, left comments, and forwarded back.

@mdaworthington  is now responsible for subsequent correspondence.

**Comment by mdaworthington** [comment]
@laynekeanna reviewed and sent back, with a couple of comments addressing some points again. CCd you so feel free to have a look again.

**Comment by laynelafrance** [comment]
Looks good, feel free to close this once Glenn gives next steps
