### ISSUE TITLE
2017 Taxes to File 

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/housekeeping#5]
Expenses and receipts since last financial year must be collected and submitted to accountant. 

Email was forwarded with documents they require. 

Wave is likely the best way to enter all expenses/receipts and this can then be forwarded to the accountant.

**Comment by laynelafrance** [comment]
I will forward all relevant receipts I have via email

**Comment by laynelafrance** [comment]
I will give you any hardcopy receipts I have next time I see you - specifically paying off deeds with the devil.

**Comment by mdaworthington** [comment]
All are documented. Just need to double check things and make sure things are in the correct places before submission.

**Comment by laynelafrance** [comment]
Sounds great, beyond wave make sure you have the other documents together from the list the accountant sent us (mainly bank statements which you can download from online banking) 
 

cc @mdaworthington
